services:
  client:
    image: chordage_client_image:v1
    ports: 
      - "8081:8080"
    networks:
      - chordage_net

  api:
    image: chordage_api_image:v1
    ports: 
      - "5001:5000"
    expose: 
      - "5000"
    networks:
      - chordage_net

networks:
  chordage_net: