apiVersion: v1
kind: Service
metadata:
  name: api-svc
  namespace: chordage
  labels:
    app: api 
spec:
  type: NodePort
  ports:
    - port: 5000
      nodePort: 30001
  selector:
    app: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: chordage
  labels:
    app: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: chordage_api_image
        imagePullPolicy: Never
        ports:
        - containerPort: 5000